FROM cgr.dev/chainguard/go AS builder

WORKDIR /app

COPY src/go.mod ./
COPY src/main.go ./

RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM cgr.dev/chainguard/static:latest

COPY --from=builder /app/main /

CMD ["./main"]